# Generated by Django 3.2.9 on 2021-12-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('coach_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tournament_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rounds', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=100)),
                ('average_score', models.FloatField()),
                ('coach', models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='api_app.coach')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(max_length=100)),
                ('player_height', models.FloatField()),
                ('average_score', models.FloatField()),
                ('no_of_games', models.IntegerField()),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='api_app.team')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('game_date', models.DateField()),
                ('home_team_score', models.FloatField(default=0)),
                ('away_team_score', models.FloatField(default=0)),
                ('round_number', models.IntegerField()),
                ('away_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='api_app.team')),
                ('away_team_from_game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_team_game', to='api_app.game')),
                ('home_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='api_app.team')),
                ('home_team_from_game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_team_game', to='api_app.game')),
                ('players', models.ManyToManyField(related_name='games', to='api_app.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='api_app.tournament')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='api_app.team')),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
    ]
